#!/bin/bash
##################################################################################################
# '''
# // @Project      Install all of the dot files instead manually install every file (Simple)
# // @Author       Saccharide
# '''
##################################################################################################

# Check if vimrc and bashrc exists, and make backup of them before override
if [ -f $HOME/.vimrc ]; then
    echo "Backing up vimrc ..."
    mv $HOME/.vimrc $HOME/.vimrc.bak
fi
if [ -f $HOME/.bashrc ]; then
    echo "Backing up bashrc ..."
    mv $HOME/.bashrc $HOME/.bashrc.bak
fi
if [ -d $HOME/.vim ]; then
    echo "Backing up .vim ..."
    mv $HOME/.vim $HOME/.vim_bak
fi

if [ -f $HOME/.gitignore ]; then
    echo "Backing up ,gitignore ..."
    mv $HOME/.gitignore $HOME/.gitignore.bak
fi
cp .gitignore $HOME/.gitignore

echo "Making a global gitignore"
git config --global core.excludesfile $HOME/.gitignore

echo "Setting default pull method to rebase"
git config --global pull.rebase true

cp .*rc $HOME
cp -R .vim $HOME
cp .tmux.conf $HOME
cp .flake8 $HOME
echo "Creating .vimtmp for persistent undo..."
mkdir $HOME/.vimtmp
mv $HOME/.vim/bundle_temp $HOME/.vim/bundle


sudo apt install -y vim vim-gtk
sudo apt install -y tmux

homebin="$HOME/bin"
if [ ! -d "$homebin" ]; then
    echo "Making $homebin"
    mkdir $homebin
fi

echo "Copying git-addons to $homebin ..."
cp git* $HOME/bin

echo "Copying saccharide.vim  to $HOME/.vim/colors ..."
cp saccharide.vim $HOME/.vim/colors

echo "Finished!"
if [[ -z $(cat ~/.bashrc | grep "export PATH=\$HOME/bin:\$PATH") ]]; then
    echo "Adding \$HOME/bin to path ..."
    echo "export PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
fi

echo "Setting git global name"
git config --global user.name "saccharide"

echo "Setting git global email"
git config --global user.email "36411557+Saccharide@users.noreply.github.com"

echo "Setting default editor to vim"
git config --global core.editor "vim"

# sudo update-alternatives --config editor

mkdir -p $HOME/.ssh

echo "Generating SSH key..."
ssh-keygen -t rsa -b 4096 -C "36411557+Saccharide@users.noreply.github.com"

echo "Your new SSH Public Key is: "

cat $HOME/.ssh/id_rsa.pub


echo "chmod 644 id_rsa.pub"
echo "chmod 600 id_rsa"

echo "Adding vim airline and clock ..."
cd $HOME/.vim/bundle
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/enricobacis/vim-airline-clock

echo "Adding vim easymotion ..."
# CHECK OUT VIM EASYMOTION, very cool, need to learn it sometimes
git clone https://github.com/easymotion/vim-easymotion

echo "Adding python syntax highlighting for vim ..."
git clone https://github.com/vim-python/python-syntax

echo "Installing black ..."
pip install black
mkdir -p ~/.vim/pack/python/start/black/plugin
mkdir -p ~/.vim/pack/python/start/black/autoload
curl https://raw.githubusercontent.com/psf/black/stable/plugin/black.vim -o ~/.vim/pack/python/start/black/plugin/black.vim
curl https://raw.githubusercontent.com/psf/black/stable/autoload/black.vim -o ~/.vim/pack/python/start/black/autoload/black.vim


echo "Installing ale (Asynchronous Lint Engine) ..."
mkdir -p ~/.vim/pack/git-plugins/start
git clone --depth 1 https://github.com/dense-analysis/ale.git ~/.vim/pack/git-plugins/start/ale


echo "Installing flake8, config file can be placed in ~/.flake8 ..."
git clone --recursive https://github.com/andviro/flake8-vim.git
mkdir -p ~/.vim/pack/flake8/start/
cd ~/.vim/pack/flake8/start/
git clone https://github.com/nvie/vim-flake8.git


echo "Installing solidity syntax highlighting ..."
git clone https://github.com/tomlion/vim-solidity.git ~/.vim/bundle/vim-solidity
cd $HOME
source $HOME/.bashrc
