#!/bin/bash
##################################################################################################
# '''
# // @Project      Install all of the dot files instead manually install every file (Simple)
# // @Author       Saccharide
# '''
##################################################################################################

# Check if vimrc and bashrc exists, and make backup of them before override
if [ -f $HOME/.vimrc ]; then
    echo "Backing up vimrc ..."
    mv $HOME/.vimrc $HOME/.vimrc_backup
fi
if [ -f $HOME/.bashrc ]; then
    echo "Backing up bashrc ..."
    mv $HOME/.bashrc $HOME/.bashrc_backup
fi
if [ -d $HOME/.vim ]; then
    echo "Backing up .vim ..."
    mv $HOME/.vim $HOME/.vim_backup
fi
cp .*rc $HOME
cp -R .vim $HOME
echo "Creating .vimtmp for persistent undo..."
mkdir $HOME/.vimtmp
mv $HOME/.vim/bundle_temp $HOME/.vim/bundle


homebin="$HOME/bin"
if [ ! -d "$homebin" ]; then
    echo "Making $homebin"
    mkdir $homebin
fi

echo "Copying git-addons to $homebin ..."

cp git* $HOME/bin

echo "Finished!"
if [[ -z $(cat ~/.bashrc | grep "export PATH=\$HOME/bin:\$PATH") ]]; then
    echo "Adding \$HOME/bin to path ..."
    echo "export PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
fi

echo "Setting git global name"
git config --global user.name "saccharide"

echo "Setting git global email"
git config --global user.email "36411557+Saccharide@users.noreply.github.com"
