#!/bin/bash
##################################################################################################
# '''
# // @Project      Install all of the dot files instead manually install every file (Simple)
# // @Author       Saccharide
# '''
##################################################################################################

# Check if vimrc and bashrc exists, and make backup of them before override
if [ -f $HOME/.vimrc ]; then
    echo "Backing up vimrc ..."
    mv $HOME/.vimrc $HOME/.vimrc.bak
fi
if [ -f $HOME/.bashrc ]; then
    echo "Backing up bashrc ..."
    mv $HOME/.bashrc $HOME/.bashrc.bak
fi
if [ -d $HOME/.vim ]; then
    echo "Backing up .vim ..."
    mv $HOME/.vim $HOME/.vim_bak
fi

if [ -f $HOME/.gitignore ]; then
    echo "Backing up ,gitignore ..."
    mv $HOME/.gitignore $HOME/.gitignore.bak
fi
cp .gitignore $HOME/.gitignore

echo "Making a global gitignore"
git config --global core.excludesfile $HOME/.gitignore


cp .*rc $HOME
cp -R .vim $HOME
cp .tmux.conf $HOME
echo "Creating .vimtmp for persistent undo..."
mkdir $HOME/.vimtmp
mv $HOME/.vim/bundle_temp $HOME/.vim/bundle


homebin="$HOME/bin"
if [ ! -d "$homebin" ]; then
    echo "Making $homebin"
    mkdir $homebin
fi

echo "Copying git-addons to $homebin ..."
cp git* $HOME/bin

echo "Copying saccharide.vim  to $HOME/.vim/colors ..."
cp saccharide.vim $HOME/.vim/colors

echo "Finished!"
if [[ -z $(cat ~/.bashrc | grep "export PATH=\$HOME/bin:\$PATH") ]]; then
    echo "Adding \$HOME/bin to path ..."
    echo "export PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
fi

echo "Setting git global name"
git config --global user.name "saccharide"

echo "Setting git global email"
git config --global user.email "36411557+Saccharide@users.noreply.github.com"

mkdir -p $HOME/.ssh

echo "Generating SSH key..."
ssh-keygen -t rsa -b 4096 -C "36411557+Saccharide@users.noreply.github.com"

echo "Your new SSH Public Key is: "

cat $HOME/.ssh/id_rsa.pub


echo "chmod 644 id_rsa.pub"
echo "chmod 600 id_rsa"

echo "Adding vim airline and clock"
cd $HOME/.vim/bundle
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/enricobacis/vim-airline-clock

echo "Adding vim easymotion"
# CHECK OUT VIM EASYMOTION, very cool, need to learn it sometimes
git clone https://github.com/easymotion/vim-easymotion

